Update Bitcanna to v1.6.1
akash-network/cosmos-omnibus pull request #438
Opened 2023-03-16 12:39 UTC by rodri-r

2023-03-17 15:01 UTC, andy108369 commented
@tombeynon FYI: this is @rodri-r 's first PR.
I'll try to check it on Monday

2023-03-22 14:51 UTC, andy108369 commented on bitcanna/build.yml
> +      - MONIKER=R-Node
please keep moniker as `node_1` just like the rest of the projects.

2023-03-22 14:53 UTC, andy108369 commented on bitcanna/deploy.yml
> -          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
please keep these.
each project has them set as this helps to default the deployments to tested/curated providers.

2023-03-22 14:53 UTC, andy108369 commented on bitcanna/docker-compose.yml
> +      - MONIKER=R-Drone
please keep moniker as `node_1` just like the rest of the projects.

2023-03-22 14:55 UTC, andy108369 commented on bitcanna/docker-compose.yml
> -      - ../.env
please keep this. The rest of the projects use that for specifying the S3 creds.

2023-03-22 14:57 UTC, andy108369 requested changes
I think all you need is just to bump the version numbers. :-)

1. Please address to the requested changes (comments)
2. Please bump bitcanna version in the `.github/workflows/publish.yml` file as well.

Let me know if you have any questions / or need any help!

2023-03-23 17:21 UTC, rodri-r commented
Thank you Andy, I have made the requested changes.  

I thought that when the PR got merged and the new release cut, actions would automatically grab my image and rename things to ghcr.io/akash-network/

2023-03-24 14:46 UTC, tombeynon commented
Hey @rodri-r thanks so much for the PR. As per Andrey's comments, really we just want to change the version number and nothing else. Check the 'Files Changed' tab on Github to make sure nothing else has slipped through, there are still a few other changes.

Ultimately the process for a chain upgrade is just to find and replace the version number in most cases. Sometimes GOLANG_VERSION needs to be updated in build.yml if a newer Go version is required (default is 1.18 currently).

2023-03-25 05:01 UTC, rodri-r commented
Thank you @tombeynon I understand now, I will make the changes.

2023-04-04 21:52 UTC, tombeynon commented
Awesome thanks @rodri-r! There should be a couple more files, mainly `.github/workflows/publish.yml` and the main project `README.md`. Can you search for `v1.5.3` and see if there are any more matches?

2023-04-05 09:41 UTC, rodri-r reviewed
Upgraded to v1.6.3

2023-04-05 09:44 UTC, rodri-r commented
Thanks @tombeynon I think I have it now in the new upgrade to v1.6.3

2023-04-05 13:48 UTC, tombeynon commented
Lovely thanks for going straight to 1.6.3. Just README.md in the project root is missing now

2023-04-06 03:11 UTC, rodri-r commented
Damn, forgot that Readme. :s 
I've made changes, think it is good now.  Next PR, I will try to send upgrades in batches. Thank you again.

2023-04-06 08:35 UTC, andy108369 commented
> Next PR, I will try to send upgrades in batches

No need doing that in batches :D
Ideal PR is to make one logical change in a single PR.

And yours looks great now! :-)

2023-04-06 09:18 UTC, andy108369 approved these changes

2023-04-17 17:30 UTC, merged